global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rslvd_rules.yml"

scrape_configs:
  - job_name: 'rslvd'
    static_configs:
      - targets: ['rslvd:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093